Repository werkbot/framewerk, pull requests merged in 2022-07, with the labels that each got.

#33 Added release drafter and package version updater
  .github/release-drafter.yml
  .github/workflows/draftrelease.yml
  package.json
Labels: enhancement

#35 Dart sass
  package-lock.json
  package.json
  sass/base/layout/_layout.scss
  sass/base/space/_space.scss
  sass/elements/typography/_typography.scss
  sass/elements/typography/elements/_p.scss
  sass/variables/_theme.scss
Labels: minor

#38 bugfix - Button Border
  sass/components/button/_button.scss
Labels: bug, patch

#39 bugfix - email fields being shrunk
  js/form.js
Labels: bug, patch
